name: Build, Dockerize, and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Added distribution parameter

      # Build with Maven
      - name: Build with Maven
        run: |
          cd course-api
          mvn clean install

      # Docker Build and Push
      - name: Docker Build and Push
        run: |
          cd course-api
          docker build -t vishakha103/course-api:latest .
          docker push vishakha103/course-api:latest
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}
